security:
  secret: "357638792F423F4428472B4B6250655368566D597133743677397A2443264629"
  front_url: "http://localhost:3000/"
spring:
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss
  datasource:
    url: jdbc:postgresql://localhost:61500/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop