security:
  secret: "357638792F423F4428472B4B6250655368566D597133743677397A2443264629"
  front_url: "http://localhost:3000/"
spring:
  threads:
    virtual:
      enabled: true
  jmx:
    enabled: true
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss
  datasource:
    url: jdbc:postgresql://localhost:61500/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/gddkia-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

management:
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always



jwt:
  auth:
    converter:
      resource-id: gddkia-client-id
      principle-attribute: preferred_username